export const roleTechniques = {
    "Copywriter": "few",
    "Social Media Strategist": "few",
    "Data Analyst": "cot",
    "UX Designer": "cot",
    "Teacher": "few",
    "Marketing Manager": "few",
    "Customer Service Agent": "zero",
    "Psychologist": "cot",
    "Developer": "cot",
    "Project Manager": "multi",
    "SEO Specialist": "few",
    "Financial Advisor": "cot",
    "Translator": "zero",
    "HR Specialist": "few",
    "Legal Advisor": "cot",
    "Sales Representative": "few",
    "Growth Hacker": "multi",
    "Business Analyst": "cot",
    "Product Manager": "multi",
    "Healthcare Assistant": "zero",
    "Operations Manager": "multi",
    "Event Planner": "few",
    "Academic Researcher": "cot",
    "Storyteller": "few",
    "Prompt Engineer": "react",
    "Startup Founder": "multi",
    "Sociologist": "cot",
    "E-learning Designer": "multi",
    "Customer Experience Designer": "cot",
    "Brand Strategist": "few",
    "AI Ethicist": "reflexion",
    "Data Scientist": "cot",
    "Software Tester": "react",
    "Economist": "cot",
    "Creative Director": "few",
    "Motion Designer": "few",
    "Community Manager": "few",
    "Recruiter": "few",
    "UX Researcher": "cot",
    "AI Tutor": "cot",
    "Speechwriter": "few",
    "Philosopher": "cot",
    "Coach Motivazionale": "few",
  };
  